name: getx_map
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  badges: ^2.0.1
  convert: ^3.0.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  flexible_polyline:
    git:
      url: https://github.com/heremaps/flexible-polyline.git
      path: dart
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_config: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: any
  flutter_native_splash: ^2.0.4
  flutter_polyline_points: ^1.0.0
  flutter_slidable: ^1.2.0
  geolocator: ^8.2.0
  get: ^4.3.7
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.1
  google_mobile_ads: ^1.1.0
  html: ^0.15.0
  internet_connection_checker: ^0.0.1+2
  jp_prefecture: ^2.0.0
  permission_handler: ^9.0.1
  sizer: ^2.0.13
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.9
  video_player: ^2.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/icon/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/get_map_icon_0.png'

flutter_native_splash:
  image: 'assets/icon/get_map_icon_0.png'
  color: 'ffbe41'
